services:
    postgresql:
      image: postgres:13
      container_name: postgres
      restart: always
      ports:
        - '9000:5432'
      volumes:
        - 'postgresql:/var/lib/postgres/data/'
      networks:
        - main
      env_file: .env

volumes:
  postgresql:

networks:
  main: